name: Timeliner
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  timeline_list: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/Articles/
    - assets/Big_Bang/
    - assets/Milky Way/
    - assets/Mammals/
    - assets/Dinosaurs/
    - assets/Insects/
    - assets/Fish_and_Stuff/
    - assets/Cells/
    - assets/Dinosaur_Demise/
    - assets/Reptiles/
    - assets/World_War_I/
    - assets/Moon/
    - assets/Newton/
    - assets/Cold_war/
    - assets/Crusades/
    - assets/Homo_Sapiens_Sapiens/
    - assets/Nelson Mandela_v2/
    - assets/Martin Luther king/
    - assets/Sufraggette_movement/
    - assets/Marie_Curie/
    - assets/Amelia_Earhart/
    - assets/Alan_Turing/
    - assets/World_War_II/
    - assets/Darwin 2/
    - assets/Internet/
    - assets/Agricultural_evolution/
    - assets/Writing/
    - assets/Recorded_history/
    - assets/Pyramid/
    - assets/Roma/
    - assets/Industrialization/
    - assets/Constantinople/
    - assets/BlackPlague/
    - assets/First_Temple/
    - assets/Apes/
    - assets/Constructive_Tools/
    - assets/Fire/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
